# find  magma_* | sed "s/magma_/'/" | sed "s/\.h/',/"
{% set magma_headers = [
  'auxiliary',
  'batched',
  'bulge',
  'cbatched',
  'cbulge',
  'cbulgeinc',
  'cgehrd_m',
  'c',
  'clapack',
  'config',
  'copy',
  'copy_v1',
  'cvbatched',
  'dbatched',
  'dbulge',
  'dbulgeinc',
  'dgehrd_m',
  'd',
  'dlapack',
  'ds',
  'dvbatched',
  'hbatched',
  'htc',
  'lapack',
  'mangling_cmake',
  'mangling',
  'operators',
  'sbatched',
  'sbulge',
  'sbulgeinc',
  'sgehrd_m',
  's',
  'slapack',
  'svbatched',
  'types',
  'v2',
  'vbatched',
  'zbatched',
  'zbulge',
  'zbulgeinc',
  'zc',
  'zgehrd_m',
  'z',
  'zlapack',
  'zvbatched'
] %}

{% set magmasparse_headers = [
  'c',
  'd',
  'ds',
  'mmio',
  's',
  'types',
  'zc',
  'z'
] %}

{% set magmablas_headers = [
  'c',
  'c_v1',
  'c_v1_map',
  'd',
  'ds',
  'ds_v1',
  'ds_v1_map',
  'd_v1',
  'd_v1_map',
  'h',
  's',
  's_v1',
  's_v1_map',
  'v1',
  'v1_map',
  'zc',
  'zc_v1',
  'zc_v1_map',
  'z',
  'z_v1',
  'z_v1_map'
] %}

{% set version = "2.9.0" %}

package:
  name: libmagma
  version: {{ version }}

source:
  - url: https://icl.utk.edu/projectsfiles/magma/downloads/magma-{{ version }}.tar.gz
    sha256: ff77fd3726b3dfec3bfb55790b06480aa5cc384396c2db35c56fdae4a82c641c
  - path: make.inc

build:
  number: 3
  skip: true  # [cuda_compiler_version == "None"]
  # debugging skips below
  # skip: true  # [not (linux64 and cuda_compiler_version == "12.9")]
  run_exports:
    - {{ pin_subpackage('libmagma', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - {{ stdlib('c') }}
    - cmake >=3.20,<4
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - m2-coreutils  # [win]
    - m2-make  # [win]
    - m2-perl  # [win]
    - make  # [unix]
    - ninja
    - python
  host:
    - cuda-version {{ cuda_compiler_version }}
    - cuda-cudart-dev
    - libcublas-dev
    - libcusparse-dev
    - liblapack
    - libblas
    - nomkl

test:
  commands:
    - test ! -f $PREFIX/include/magma.h                        # [unix]
    - if exist %LIBRARY_PREFIX%\include\magma.h exit 1         # [win]
    - test -f $PREFIX/lib/libmagma${SHLIB_EXT}                 # [unix]
    - if not exist %LIBRARY_PREFIX%\lib\magma.lib exit 1       # [win]
    - if not exist %LIBRARY_PREFIX%\bin\magma.dll exit 1       # [win]
    - test ! -f $PREFIX/lib/libmagma_sparse${SHLIB_EXT}        # [unix]
    - if exist %LIBRARY_PREFIX%\lib\magma_sparse.lib exit 1    # [win]
    - if exist %LIBRARY_PREFIX%\bin\magma_sparse.dll exit 1    # [win]
    - test ! -f $PREFIX/lib/pkgconfig/magma.pc                 # [unix]
    - if exist %LIBRARY_PREFIX%\lib\pkgconfig\magma.pc exit 1  # [win]
{% for each_header in magma_headers %}
    - test ! -f $PREFIX/include/magma_{{ each_header }}.h                 # [unix]
    - if exist %LIBRARY_PREFIX%\include\magma_{{ each_header }}.h exit 1  # [win]
{% endfor %}
{% for each_header in magmasparse_headers %}
    - test ! -f $PREFIX/include/magmasparse_{{ each_header }}.h                 # [unix]
    - if exist %LIBRARY_PREFIX%\include\magmasparse_{{ each_header }}.h exit 1  # [win]
{% endfor %}
{% for each_header in magmablas_headers %}
    - test ! -f $PREFIX/include/magmablas_{{ each_header }}.h                 # [unix]
    - if exist %LIBRARY_PREFIX%\include\magmablas_{{ each_header }}.h exit 1  # [win]
{% endfor %}

about:
  home: https://icl.utk.edu/magma/
  dev_url:  https://github.com/icl-utk-edu/magma/
  summary: Matrix Algebra on GPU and Multicore Architectures
  license: BSD-3-Clause
  license_file: COPYRIGHT

extra:
  recipe-maintainers:
    - carterbox
    - conda-forge/pytorch-cpu
